apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://backend:9000
            - name: REACT_APP_KEYCLOAK_URL
              value: http://keycloak:8080
            - name: TENANT_MODE
              value: multi
          image: frontend
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
