apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mcp-server
  name: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mcp-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: mcp-server
    spec:
      containers:
        - image: mcp-server
          name: mcp-server
          ports:
            - containerPort: 3002
              protocol: TCP
      restartPolicy: Always
