apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: n8n-data
  name: n8n-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
